services:
  compose-dashboard:
    image: "mcr.microsoft.com/dotnet/nightly/aspire-dashboard:latest"
    ports:
      - "18888:18888"
    expose:
      - "18889"
      - "18890"
    networks:
      - "aspire"
    restart: "always"
  pg:
    image: "docker.io/library/postgres:17.6"
    environment:
      POSTGRES_HOST_AUTH_METHOD: "scram-sha-256"
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256 --auth-local=scram-sha-256"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "${PG_PASSWORD}"
    expose:
      - "5432"
    networks:
      - "aspire"
  rabbit:
    image: "docker.io/library/rabbitmq:4.2"
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "${RABBIT_PASSWORD}"
    expose:
      - "5672"
    networks:
      - "aspire"
  identity:
    image: "${IDENTITY_IMAGE}"
    environment:
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
      HTTP_PORTS: "${IDENTITY_PORT}"
      ConnectionStrings__identitydb: "Host=pg;Port=5432;Username=postgres;Password=${PG_PASSWORD};Database=identitydb"
      IDENTITYDB_HOST: "pg"
      IDENTITYDB_PORT: "5432"
      IDENTITYDB_USERNAME: "postgres"
      IDENTITYDB_PASSWORD: "${PG_PASSWORD}"
      IDENTITYDB_URI: "postgresql://postgres:${PG_PASSWORD}@pg:5432/identitydb"
      IDENTITYDB_JDBCCONNECTIONSTRING: "jdbc:postgresql://pg:5432/identitydb"
      IDENTITYDB_DATABASENAME: "identitydb"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://compose-dashboard:18889"
      OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
      OTEL_SERVICE_NAME: "identity"
    ports:
      - "${IDENTITY_PORT}"
    networks:
      - "aspire"
  patient-registry:
    image: "${PATIENT_REGISTRY_IMAGE}"
    environment:
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
      HTTP_PORTS: "${PATIENT_REGISTRY_PORT}"
      ConnectionStrings__patientdb: "Host=pg;Port=5432;Username=postgres;Password=${PG_PASSWORD};Database=patientdb"
      PATIENTDB_HOST: "pg"
      PATIENTDB_PORT: "5432"
      PATIENTDB_USERNAME: "postgres"
      PATIENTDB_PASSWORD: "${PG_PASSWORD}"
      PATIENTDB_URI: "postgresql://postgres:${PG_PASSWORD}@pg:5432/patientdb"
      PATIENTDB_JDBCCONNECTIONSTRING: "jdbc:postgresql://pg:5432/patientdb"
      PATIENTDB_DATABASENAME: "patientdb"
      ConnectionStrings__rabbit: "amqp://guest:${RABBIT_PASSWORD}@rabbit:5672"
      RABBIT_HOST: "rabbit"
      RABBIT_PORT: "5672"
      RABBIT_USERNAME: "guest"
      RABBIT_PASSWORD: "${RABBIT_PASSWORD}"
      RABBIT_URI: "amqp://guest:${RABBIT_PASSWORD}@rabbit:5672"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://compose-dashboard:18889"
      OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
      OTEL_SERVICE_NAME: "patient-registry"
    ports:
      - "${PATIENT_REGISTRY_PORT}"
    networks:
      - "aspire"
  encounters:
    image: "${ENCOUNTERS_IMAGE}"
    environment:
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
      HTTP_PORTS: "${ENCOUNTERS_PORT}"
      ConnectionStrings__encounterdb: "Host=pg;Port=5432;Username=postgres;Password=${PG_PASSWORD};Database=encounterdb"
      ENCOUNTERDB_HOST: "pg"
      ENCOUNTERDB_PORT: "5432"
      ENCOUNTERDB_USERNAME: "postgres"
      ENCOUNTERDB_PASSWORD: "${PG_PASSWORD}"
      ENCOUNTERDB_URI: "postgresql://postgres:${PG_PASSWORD}@pg:5432/encounterdb"
      ENCOUNTERDB_JDBCCONNECTIONSTRING: "jdbc:postgresql://pg:5432/encounterdb"
      ENCOUNTERDB_DATABASENAME: "encounterdb"
      ConnectionStrings__rabbit: "amqp://guest:${RABBIT_PASSWORD}@rabbit:5672"
      RABBIT_HOST: "rabbit"
      RABBIT_PORT: "5672"
      RABBIT_USERNAME: "guest"
      RABBIT_PASSWORD: "${RABBIT_PASSWORD}"
      RABBIT_URI: "amqp://guest:${RABBIT_PASSWORD}@rabbit:5672"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://compose-dashboard:18889"
      OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
      OTEL_SERVICE_NAME: "encounters"
    ports:
      - "${ENCOUNTERS_PORT}"
    networks:
      - "aspire"
  clinical-docs:
    image: "${CLINICAL_DOCS_IMAGE}"
    environment:
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
      HTTP_PORTS: "${CLINICAL_DOCS_PORT}"
      ConnectionStrings__clinicaldocsdb: "Host=pg;Port=5432;Username=postgres;Password=${PG_PASSWORD};Database=clinicaldocsdb"
      CLINICALDOCSDB_HOST: "pg"
      CLINICALDOCSDB_PORT: "5432"
      CLINICALDOCSDB_USERNAME: "postgres"
      CLINICALDOCSDB_PASSWORD: "${PG_PASSWORD}"
      CLINICALDOCSDB_URI: "postgresql://postgres:${PG_PASSWORD}@pg:5432/clinicaldocsdb"
      CLINICALDOCSDB_JDBCCONNECTIONSTRING: "jdbc:postgresql://pg:5432/clinicaldocsdb"
      CLINICALDOCSDB_DATABASENAME: "clinicaldocsdb"
      ConnectionStrings__rabbit: "amqp://guest:${RABBIT_PASSWORD}@rabbit:5672"
      RABBIT_HOST: "rabbit"
      RABBIT_PORT: "5672"
      RABBIT_USERNAME: "guest"
      RABBIT_PASSWORD: "${RABBIT_PASSWORD}"
      RABBIT_URI: "amqp://guest:${RABBIT_PASSWORD}@rabbit:5672"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://compose-dashboard:18889"
      OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
      OTEL_SERVICE_NAME: "clinical-docs"
    ports:
      - "${CLINICAL_DOCS_PORT}"
    networks:
      - "aspire"
  medications:
    image: "${MEDICATIONS_IMAGE}"
    environment:
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
      HTTP_PORTS: "${MEDICATIONS_PORT}"
      ConnectionStrings__medsdb: "Host=pg;Port=5432;Username=postgres;Password=${PG_PASSWORD};Database=medsdb"
      MEDSDB_HOST: "pg"
      MEDSDB_PORT: "5432"
      MEDSDB_USERNAME: "postgres"
      MEDSDB_PASSWORD: "${PG_PASSWORD}"
      MEDSDB_URI: "postgresql://postgres:${PG_PASSWORD}@pg:5432/medsdb"
      MEDSDB_JDBCCONNECTIONSTRING: "jdbc:postgresql://pg:5432/medsdb"
      MEDSDB_DATABASENAME: "medsdb"
      ConnectionStrings__rabbit: "amqp://guest:${RABBIT_PASSWORD}@rabbit:5672"
      RABBIT_HOST: "rabbit"
      RABBIT_PORT: "5672"
      RABBIT_USERNAME: "guest"
      RABBIT_PASSWORD: "${RABBIT_PASSWORD}"
      RABBIT_URI: "amqp://guest:${RABBIT_PASSWORD}@rabbit:5672"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://compose-dashboard:18889"
      OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
      OTEL_SERVICE_NAME: "medications"
    ports:
      - "${MEDICATIONS_PORT}"
    networks:
      - "aspire"
  labs-docs:
    image: "${LABS_DOCS_IMAGE}"
    environment:
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
      HTTP_PORTS: "${LABS_DOCS_PORT}"
      ConnectionStrings__labsdocsdb: "Host=pg;Port=5432;Username=postgres;Password=${PG_PASSWORD};Database=labsdocsdb"
      LABSDOCSDB_HOST: "pg"
      LABSDOCSDB_PORT: "5432"
      LABSDOCSDB_USERNAME: "postgres"
      LABSDOCSDB_PASSWORD: "${PG_PASSWORD}"
      LABSDOCSDB_URI: "postgresql://postgres:${PG_PASSWORD}@pg:5432/labsdocsdb"
      LABSDOCSDB_JDBCCONNECTIONSTRING: "jdbc:postgresql://pg:5432/labsdocsdb"
      LABSDOCSDB_DATABASENAME: "labsdocsdb"
      ConnectionStrings__rabbit: "amqp://guest:${RABBIT_PASSWORD}@rabbit:5672"
      RABBIT_HOST: "rabbit"
      RABBIT_PORT: "5672"
      RABBIT_USERNAME: "guest"
      RABBIT_PASSWORD: "${RABBIT_PASSWORD}"
      RABBIT_URI: "amqp://guest:${RABBIT_PASSWORD}@rabbit:5672"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://compose-dashboard:18889"
      OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
      OTEL_SERVICE_NAME: "labs-docs"
    ports:
      - "${LABS_DOCS_PORT}"
    networks:
      - "aspire"
  audit:
    image: "${AUDIT_IMAGE}"
    environment:
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
      HTTP_PORTS: "${AUDIT_PORT}"
      ConnectionStrings__auditdb: "Host=pg;Port=5432;Username=postgres;Password=${PG_PASSWORD};Database=auditdb"
      AUDITDB_HOST: "pg"
      AUDITDB_PORT: "5432"
      AUDITDB_USERNAME: "postgres"
      AUDITDB_PASSWORD: "${PG_PASSWORD}"
      AUDITDB_URI: "postgresql://postgres:${PG_PASSWORD}@pg:5432/auditdb"
      AUDITDB_JDBCCONNECTIONSTRING: "jdbc:postgresql://pg:5432/auditdb"
      AUDITDB_DATABASENAME: "auditdb"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://compose-dashboard:18889"
      OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
      OTEL_SERVICE_NAME: "audit"
    ports:
      - "${AUDIT_PORT}"
    networks:
      - "aspire"
  timeline-bff:
    image: "${TIMELINE_BFF_IMAGE}"
    environment:
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
      Services__PatientRegistry__BaseUrl: "http://patient-registry:8080"
      Services__Encounters__BaseUrl: "http://encounters:8080"
      Services__ClinicalDocs__BaseUrl: "http://clinical-docs:8080"
      Services__Medications__BaseUrl: "http://medications:8080"
      Services__LabsDocs__BaseUrl: "http://labs-docs:8080"
      Services__Audit__BaseUrl: "http://audit:8080"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
      HTTP_PORTS: "${TIMELINE_BFF_PORT}"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://compose-dashboard:18889"
      OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
      OTEL_SERVICE_NAME: "timeline-bff"
    ports:
      - "${TIMELINE_BFF_PORT}"
    networks:
      - "aspire"
networks:
  aspire:
    driver: "bridge"
